MainXPos = 50
MainYPos = 100
MainWidth = 300
MainHeight = 800
DataPrefix = "FData"

[inputs]
InDev = "Dev2"
V1Chan = "ai0"
V2Chan = "ai1"
VMChan = "ai2"
SampleRate = 3000
LiveDuration = 3.0
UpdateRate = 10.0

[outputs]
OutDev = "Dev2 USB-6251 (Mass Termination)"

[graphing]
GraphWidth = 900
GraphHeight = 800
UpdateRate = 10
MainWidth = 900
MainHeight = 800
